### ISSUE TITLE
Running Dockerfile.mkl after creating image from Dockerfile.devel-mkl gives libcublas.so.9.0 No such file or directory error

### ISSUE THREAD

**Issue by mohammedayub44** [tensorflow/serving#1418]
### System information
OS: Ubuntu 16.04
Tensorflow Version: 1.12.0
Python: 3.6.8
Cuda Version: 9.0

### Steps to Reproduce
Build the optimized binary docker image from the provided docker file using the below command 
`docker build -t $USER/tensorflow-serving-devel-mkl -f /home/ubuntu/serving/tensorflow_serving/tools/docker/Dockerfile.devel-mkl2 .`
See Issues #1417 

Change Base_image to build from in the below File (Line 16) to above tagged image
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.mkl

Also modify the parameters accordingly to your architecture. 

I'm using the `docker-compose` functionality as `docker-compose up --build`
with following [docker-compose.yml.txt](https://github.com/tensorflow/serving/files/3503355/docker-compose.yml.txt) and modified [Dockerfile.mkl.txt](https://github.com/tensorflow/serving/files/3503354/Dockerfile.mkl.txt)
files. You should get the same error when you do `docker container start <container_name>`

#### Error:

`ImportError: Traceback (most recent call last):`
`  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>`
`    from tensorflow.python.pywrap_tensorflow_internal import *`
`  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>`
`    _pywrap_tensorflow_internal = swig_import_helper()`
`  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper`
`    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module`
`    return load_dynamic(name, filename, file)`
`  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic`
`    return _load(spec)`
`ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory`

#### Log File
[tf_mkl_container_logs.txt](https://github.com/tensorflow/serving/files/3503359/tf_mkl_container_logs.txt)

**Comment by gowthamkpr** [comment]
@mohammedayub44 Can you please try running Tensorflow [serving 1.14 GPU](https://hub.docker.com/r/tensorflow/serving/tags/) and let me know if the issue still persists. Thanks!

**Comment by mohammedayub44** [comment]
@gowthamkpr  
Sorry, I meant I wanted to use the Intel Optimized Tensorflow Binaries on CPU because I was getting `You CPU supports instructions that this  binary was not compiled to use: AVX2 FMA` 
To avoid this error I went down this path of compiling my own image from mkl dockerfiles. 
My guess was it should work on CPU without prompting GPU related errors.  Are `Dockerfile.devel.mkl` and `Dockerfile.mkl` are for CPU only ?

**Comment by mohammedayub44** [comment]
@gowthamkpr 
Tried with `latest-gpu` and `1.14.0-gpu` both give the same error while using building a custom docker image from it. `ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory` 
They work correctly when run outside the custom docker image, also I don't see this problem with `1.11.0-gpu`, this works fine both locally and inside my docker image without any issues. Looks like something changed in the new versions with and ts not able to fetch cuda related files.

**Comment by mohammedayub44** [comment]
This works now. Silly error on my part, I was overriding (manually installing) the tensorflow versions using a requirements.txt file (which gets generated from my local environment) in my dockerfile.mkl file. I did this because my Client app was not able to find the tensorflow libraries in the base image.

Solution - If installing tensorflow manually inside the docker image, verify its the same version as the base docker image. i.e. if your using `1.14.0-gpu` as base image to build, install the `tensorflow==1.14.0` `tensorflow-gpu==1.14.0`

Closing for now as its resolved.
Thanks !
