### ISSUE TITLE
could not create cudnn handle with lstm layer

### ISSUE THREAD

**Issue by tienthaict96** [tensorflow/serving#1500]
I am using tensorflow serving with Docker (gpu). I launched the service:
```bash
docker run --rm --gpus all -p 8500:8500 \
--mount type=bind,source=`pwd` /exported,target=/models/OCR \
-e MODEL_NAME=OCR -t tensorflow/serving:1.14.0-gpu &
```
## Network architecture
``` python
input_tensor = Input(name='the_input', shape=(220, 40, 3), dtype='float32')
x = input_tensor
for i, n_cnn in enumerate([2, 2, 3]):
    for j in range(n_cnn):
        x = Conv2D(32*2**min(i, 3), kernel_size=3, padding='same', kernel_initializer='he_uniform')(x)
        x = BatchNormalization()(x)
        x = Activation('relu')(x)
    x = MaxPooling2D(2 if i < 3 else (2, 1))(x)
x = Reshape(target_shape=(27, 5 * 128))(x)
rnn_size = 128
x = Bidirectional(LSTM(rnn_size, return_sequences=True))(x)
x = Bidirectional(LSTM(rnn_size, return_sequences=True))(x)
x = Dense(NUM_CHARS+1)(x)
y_pred = Activation('softmax')(x)

model = Model(inputs=[input_tensor], outputs=y_pred)
```
When I run the python client, I got following error:
```bash
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1_1/convolution}}]]
	 [[activation_8_1/truediv/_253]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1_1/convolution}}]]
0 successful operations.
0 derived errors ignored."
	debug_error_string = "{"created":"@1575087463.331189464","description":"Error received from peer ipv4:127.0.0.1:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"2 root error(s) found.\n  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\n\t [[{{node conv2d_1_1/convolution}}]]\n\t [[activation_8_1/truediv/_253]]\n  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\n\t [[{{node conv2d_1_1/convolution}}]]\n0 successful operations.\n0 derived errors ignored.","grpc_status":2}"
>
```
If I use the docker image cpu version or remove lstm layer, the problem will no longer exists (results is True).

## Environment info
Docker: 19.03.5
Image: tensorflow/serving:1.14.0-gpu (same on lastest, 2.0.0)
OS: ubuntu 18.04 (same on 16.04)
Python: 3.6
Tensorflow: 1.14 (same on 2.0.0, 1.15)
GPU: Gtx 1650

**Comment by gowthamkpr** [comment]
@tienthaict96 I don't think this issue is related to Tensorflow serving. 

I've seen this error message for three different reasons, with different solutions:

**1. You have cache issues**
I regularly work around this error by shutting down my python process, removing the ~/.nv directory (on linux, rm -rf ~/.nv), and restarting the Python process. I don't exactly know why this works. It's probably at least partly related to the second option:

**2. You're out of memory**
The error can also show up if you run out of graphics card RAM. With an nvidia GPU you can check graphics card memory usage with nvidia-smi. This will give you not only a readout of how much GPU RAM you have in use (something like 6025MiB /  6086MiB if you're almost at the limit) as well as a list of what processes are using GPU RAM.

If you've run out of RAM, you'll need to restart the process (which should free up the RAM) and then take a less memory-intensive approach. A few options are:

> reducing your batch size
> using a simpler model
> using less data
> limit TensorFlow GPU memory fraction: For example, the following will make sure TensorFlow uses <= 90% of your RAM:
> import keras
> import tensorflow as tf
> 

```
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.9
keras.backend.tensorflow_backend.set_session(tf.Session(config=config))
```
This can slow down your model evaluation if not used together with the items above, presumably since the large data set will have to be swapped in and out to fit into the small amount of memory you've allocated.

3. You have incompatible versions of CUDA, TensorFlow, NVIDIA drivers, etc.
If you've never had similar models working, you're not running out of VRAM and your cache is clean, I'd go back and set up CUDA + TensorFlow using the best available installation guide - I have had the most success with following the instructions at https://www.tensorflow.org/install/gpu rather than those on the NVIDIA / CUDA site.

For more information you can refer to the following question [here](https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in). Thanks!

**Comment by tienthaict96** [comment]
@gowthamkpr tks for the comment. The issue was resolved.
