### ISSUE TITLE
Call saved model inbuilt functions while sending a post request to the saved model

### ISSUE THREAD

**Issue by kothari1997narayan** [tensorflow/serving#1898]
Below is my tfrs model CLI, and I want to use the  Function Name: 'query_with_exclusions' while sending a post request.
How can I use it..
The model is [tfrs.layers.factorized_top_k.ScaNN](https://www.tensorflow.org/recommenders/api_docs/python/tfrs/layers/factorized_top_k/ScaNN)

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_1'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_input_1:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: StatefulPartitionedCall:0
    outputs['output_2'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 10)
        name: StatefulPartitionedCall:1
  Method name is: tensorflow/serving/predict
WARNING: Logging before flag parsing goes to stderr.
W0725 11:18:40.632589 140348277434240 deprecation.py:506] From /usr/local/lib/python2.7/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling __init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2021-07-25 11:18:40.764407: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-07-25 11:18:40.781666: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-07-25 11:18:40.781756: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (f0ce2f298596): /proc/driver/nvidia/version does not exist
2021-07-25 11:18:40.813537: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2021-07-25 11:18:40.814208: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55881893ef40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-07-25 11:18:40.814254: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
W0725 11:18:40.854746 140348277434240 util.py:148] Unused attribute in object (root).query_model.layer_with_weights-0._table: [u'table', u'table']
W0725 11:18:40.854959 140348277434240 util.py:152] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.

Defined Functions:
  Function Name: '__call__'
    Option #1
      Callable with:
        Argument #1
          queries: TensorSpec(shape=(None,), dtype=tf.string, name=u'queries')
        Argument #2
          DType: NoneType
          Value: None
        Argument #3
          DType: bool
          Value: False
    Option #2
      Callable with:
        Argument #1
          input_1: TensorSpec(shape=(None,), dtype=tf.string, name=u'input_1')
        Argument #2
          DType: NoneType
          Value: None
        Argument #3
          DType: bool
          Value: False
    Option #3
      Callable with:
        Argument #1
          queries: TensorSpec(shape=(None,), dtype=tf.string, name=u'queries')
        Argument #2
          DType: NoneType
          Value: None
        Argument #3
          DType: bool
          Value: True
    Option #4
      Callable with:
        Argument #1
          input_1: TensorSpec(shape=(None,), dtype=tf.string, name=u'input_1')
        Argument #2
          DType: NoneType
          Value: None
        Argument #3
          DType: bool
          Value: True

  Function Name: '_default_save_signature'
    Option #1
      Callable with:
        Argument #1
          input_1: TensorSpec(shape=(None,), dtype=tf.string, name=u'input_1')

  Function Name: 'call_and_return_all_conditional_losses'
    Option #1
      Callable with:
        Argument #1
          input_1: TensorSpec(shape=(None,), dtype=tf.string, name=u'input_1')
        Argument #2
          DType: NoneType
          Value: None
        Argument #3
          DType: bool
          Value: False
    Option #2
      Callable with:
        Argument #1
          input_1: TensorSpec(shape=(None,), dtype=tf.string, name=u'input_1')
        Argument #2
          DType: NoneType
          Value: None
        Argument #3
          DType: bool
          Value: True
    Option #3
      Callable with:
        Argument #1
          queries: TensorSpec(shape=(None,), dtype=tf.string, name=u'queries')
        Argument #2
          DType: NoneType
          Value: None
        Argument #3
          DType: bool
          Value: False
    Option #4
      Callable with:
        Argument #1
          queries: TensorSpec(shape=(None,), dtype=tf.string, name=u'queries')
        Argument #2
          DType: NoneType
          Value: None
        Argument #3
          DType: bool
          Value: True

  Function Name: 'query_with_exclusions'
    Option #1
      Callable with:
        Argument #1
          queries: TensorSpec(shape=(1,), dtype=tf.string, name=u'queries')
        Argument #2
          exclusions: TensorSpec(shape=(1, 2), dtype=tf.string, name=u'exclusions')
        Argument #3
          DType: int
          Value: 15

```

**Comment by kothari1997narayan** [comment]
Using these link solved my problem
https://towardsdatascience.com/how-to-extend-a-keras-model-5effc083265c
https://www.kdnuggets.com/2020/07/building-rest-api-tensorflow-serving-part-1.html
