### ISSUE TITLE
bazel GPU build error with fatal error: external/nccl_archive/src/nccl.h: No such file or directory

### ISSUE THREAD

**Issue by cheyang** [tensorflow/serving#327]
We are trying to build Tensorflow Serving 0.5.1 with [TensorFlow 1.0.0@07bb8ea](https://github.com/tensorflow/tensorflow/commit/07bb8ea2379bd459832b23951fb20ec47f3fdbd4)

Basing on CUDA 7.5, cuDNN 5.
Bazel 0.4.4

```
cd serving && bazel build -c opt --config=cuda tensorflow_serving/...
```

```
ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe0160
8c/external/org_tensorflow/tensorflow/contrib/nccl/BUILD:23:1: C++ c
ompilation of rule '@org_tensorflow//tensorflow/contrib/nccl:python/
ops/_nccl_ops.so' failed: crosstool_wrapper_driver_is_not_gcc failed
: error executing command external/local_config_cuda/crosstool/clang
/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTI
FY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-paramete
r ... (remaining 76 argument(s) skipped): com.google.devtools.build.
lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/org_tensorflow/tensorflow/contrib/ncc
l/kernels/nccl_manager.cc:15:0:
external/org_tensorflow/tensorflow/contrib/nccl/kernels/nccl_manager
.h:23:44: fatal error: external/nccl_archive/src/nccl.h: No such fil
e or directory
 #include "external/nccl_archive/src/nccl.h"
                                            ^
compilation terminated.
INFO: Elapsed time: 147.378s, Critical Path: 107.11s
```

I'm able to find nccl.h, but it can't be found during bazel build. Any suggestions? Thanks in advanced.
```
find / -name nccl.h
/root/.cache/bazel/_bazel_root/5071e8dca1385fb776f72b33971bf157/exte
rnal/nccl_archive/src/nccl.h
/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/exte
rnal/nccl_archive/src/nccl.h
```

**Comment by tvkpz** [comment]
Same error here.

ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/contrib/nccl/BUILD:23:1: C++ compilation of rule '@org_tensorflow//tensorflow/contrib/nccl:python/ops/_nccl_ops.so' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 77 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/org_tensorflow/tensorflow/contrib/nccl/kernels/nccl_manager.cc:15:0:
external/org_tensorflow/tensorflow/contrib/nccl/kernels/nccl_manager.h:23:44: fatal error: external/nccl_archive/src/nccl.h: No such file or directory
compilation terminated.

Any solutions?

**Comment by cheyang** [comment]
@ kirilg，can you help take a quick look at this issue? Thank you.

**Comment by kinhunt** [comment]
same here
<img width="831" alt="2017-02-24 1 05 02" src="https://cloud.githubusercontent.com/assets/1231514/23291235/f4372210-fa91-11e6-9b39-00f1d3e0f2a3.png">

**Comment by jlertle** [comment]
To get around it you can comment out the DEP for nccl in: tensorflow/tensorflow/contrib/BUILD

Line 42 iirc

**Comment by cheyang** [comment]
Thanks, @jlertle

**Comment by sskgit** [comment]
Thanks @jlertle.

**Comment by cosastro** [comment]
which line in: tensorflow/tensorflow/contrib/BUILD is the DEP for nccl? i can't find it, thanks.

**Comment by perdasilva** [comment]
41: //tensorflow/contrib/nccl:nccl_py

**Comment by perdasilva** [comment]
I believe...

**Comment by jlertle** [comment]
It was moved into a Windows check but the referenced path is still having issues resolving during Serving build process on Ubuntu. Bazel stuff.

**Comment by cosastro** [comment]
I tried a script provided by #318, it could works fine

**Comment by skonto** [comment]
If you comment it out examples fail.

**Comment by skonto** [comment]
I solved by removing the prefix /external/nccl_archive.

**Comment by Lukeisme** [comment]
@skonto removing prefix /external/nccl_archive in files **nccl_ops.cc**  and 
**nccl_manager.h** which in folder tensorflow/tensorflow/contrib/nccl/kernels, fix the issue

**Comment by perdasilva** [comment]
git clone https://github.com/NVIDIA/nccl.git
cd nccl/
make CUDA_HOME=/usr/local/cuda

# the following commands may need sudo
make install 
mkdir -p /usr/local/include/external/nccl_archive/src
ln -s /usr/local/include/nccl.h /usr/local/include/external/nccl_archive/src/nccl.h

**Comment by tomodachi21** [comment]
I used @perdasilva fix and was able to get it to compile but it fails with the last 10 or so tests. When trying to run the syntaxnet/demo.sh script it looks like it recognizes the GPU (K80) but then dies with a segmentation fault. I did not comment out the nccl_py but instead downloaded the nccl.git above and executed the lines as they were listed - it compiles (fails tests) but compiles. Any idea why I'm getting this segmentation fault? 

`2017-06-29 13:40:28.569661: W external/org_tensorflow/tensorflow/stream_executor/stream.cc:1550] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 161, in <module>
    tf.app.run()
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 157, in main
    Eval(sess)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 130, in Eval
    parser.evaluation['documents'],
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : a.shape=(1, 1040), b.shape=(1040, 64), m=1, n=64, k=1040
	 [[Node: evaluation/while/layer_0/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](evaluation/while/concat, evaluation/while/layer_0/MatMul/Enter)]]
	 [[Node: evaluation/while/Switch_8/_95 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_156_evaluation/while/Switch_8", tensor_type=DT_STRING, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopevaluation/while/feature_4/shape/_61)]]

Caused by op u'evaluation/while/layer_0/MatMul', defined at:
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 161, in <module>
    tf.app.run()
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 157, in main
    Eval(sess)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 111, in Eval
    evaluation_max_steps=FLAGS.max_steps)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/structured_graph_builder.py", line 240, in AddEvaluation
    'features'], n['state'], use_average=self._use_averaging))
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/structured_graph_builder.py", line 128, in _BuildSequence
    parallel_iterations=100)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/ops/control_flow_ops.py", line 2623, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/ops/control_flow_ops.py", line 2456, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/ops/control_flow_ops.py", line 2406, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/structured_graph_builder.py", line 106, in Advance
    return_average=use_average)['logits']
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/graph_builder.py", line 353, in _BuildNetwork
    name='layer_%d' % i)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/ops/nn_impl.py", line 263, in relu_layer
    xw_plus_b = nn_ops.bias_add(math_ops.matmul(x, weights), biases)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/ops/math_ops.py", line 1801, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 1263, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Blas SGEMM launch failed : a.shape=(1, 1040), b.shape=(1040, 64), m=1, n=64, k=1040
	 [[Node: evaluation/while/layer_0/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](evaluation/while/concat, evaluation/while/layer_0/MatMul/Enter)]]
	 [[Node: evaluation/while/Switch_8/_95 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_156_evaluation/while/Switch_8", tensor_type=DT_STRING, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopevaluation/while/feature_4/shape/_61)]]

INFO:tensorflow:Total processed documents: 0
INFO:tensorflow:Read 0 documents
syntaxnet/demo.sh: line 56:  5721 Segmentation fault      (core dumped) $PARSER_EVAL --input=$INPUT_FORMAT --output=stdout-conll --hidden_layer_sizes=64 --arg_prefix=brain_tagger --graph_builder=structured --task_context=$MODEL_DIR/context.pbtxt --model_path=$MODEL_DIR/tagger-params --slim_model --batch_size=1024 --alsologtostderr
      5722                       (core dumped) | $PARSER_EVAL --input=stdin-conll --output=stdout-conll --hidden_layer_sizes=512,512 --arg_prefix=brain_parser --graph_builder=structured --task_context=$MODEL_DIR/context.pbtxt --model_path=$MODEL_DIR/parser-params --slim_model --batch_size=1024 --alsologtostderr
      5723                       (core dumped) | bazel-bin/syntaxnet/conll2tree --task_context=$MODEL_DIR/context.pbtxt --alsologtostderr`

**Comment by tomodachi21** [comment]
These are the tests that fail: 

```
INFO: Elapsed time: 3887.699s, Critical Path: 336.62s
//syntaxnet:arc_standard_transitions_test                                PASSED in 0.1s
//syntaxnet:binary_segment_state_test                                    PASSED in 0.1s
//syntaxnet:binary_segment_transitions_test                              PASSED in 0.1s
//syntaxnet:char_ngram_string_extractor_test                             PASSED in 0.1s
//syntaxnet:char_properties_test                                         PASSED in 0.1s
//syntaxnet:char_shift_transitions_test                                  PASSED in 0.1s
//syntaxnet:head_transitions_test                                        PASSED in 0.1s
//syntaxnet:label_transitions_test                                       PASSED in 0.1s
//syntaxnet:morphology_label_set_test                                    PASSED in 0.1s
//syntaxnet:once_transitions_test                                        PASSED in 0.1s
//syntaxnet:parser_features_test                                         PASSED in 0.1s
//syntaxnet:segmenter_utils_test                                         PASSED in 0.0s
//syntaxnet:sentence_features_test                                       PASSED in 0.1s
//syntaxnet:shared_store_test                                            PASSED in 0.3s
//syntaxnet:tagger_transitions_test                                      PASSED in 0.1s
//syntaxnet/util:check_test                                              PASSED in 1.7s
//syntaxnet/util:registry_test                                           PASSED in 1.7s
//syntaxnet:whole_sentence_features_test                                 PASSED in 0.1s
//util/utf8:unicodetext_unittest                                         PASSED in 0.1s
//syntaxnet:beam_reader_ops_test                                         FAILED in 19.3s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 14.9s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 3.3s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 14.2s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 8.5s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 5.6s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/text_formats_test/test.log

Executed 25 out of 25 tests: 19 tests pass and 6 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

```

**Comment by tomodachi21** [comment]
When doing the bazel test ... after compiling the GPU portion you get:

```
FAIL: //syntaxnet:reader_ops_test (see /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/reader_ops_test/test.log).
INFO: From Compiling syntaxnet/morpher_transitions.cc:
syntaxnet/morpher_transitions.cc: In member function 'virtual void syntaxnet::MorphologyTransitionState::AddParseToDocument(const syntaxnet::ParserState&, bool, syntaxnet::Sentence*) const':
syntaxnet/morpher_transitions.cc:105:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < tag_.size(); ++i) {
                                   ^
FAIL: //syntaxnet:parser_trainer_test (see /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/parser_trainer_test/test.log).
[5,181 / 5,184] Creating runfiles tree bazel-out/local_linux-opt/bin/syntaxnet/lexicon_builderFAIL: //syntaxnet:lexicon_builder_test (see /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/lexicon_builder_test/test.log).
FAIL: //dragnn/python:graph_builder_test (see /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/dragnn/python/graph_builder_test/test.log).
FAIL: //syntaxnet:graph_builder_test (see /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/graph_builder_test/test.log).
FAIL: //examples/dragnn:test_run_all_tutorials (see /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log).
FAIL: //syntaxnet:beam_reader_ops_test (see /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log).
INFO: Elapsed time: 4403.596s, Critical Path: 485.18s
//dragnn/components/stateless:stateless_component_test                   PASSED in 0.1s
//dragnn/components/syntaxnet:syntaxnet_component_test                   PASSED in 0.3s
//dragnn/components/syntaxnet:syntaxnet_link_feature_extractor_test      PASSED in 0.1s
//dragnn/components/syntaxnet:syntaxnet_transition_state_test            PASSED in 0.1s
//dragnn/core:beam_test                                                  PASSED in 0.3s
//dragnn/core:compute_session_impl_test                                  PASSED in 2.5s
//dragnn/core:compute_session_pool_test                                  PASSED in 0.1s
//dragnn/core:dragnn_bulk_op_kernels_test                                PASSED in 0.1s
//dragnn/core:dragnn_op_kernels_test                                     PASSED in 0.1s
//dragnn/core:index_translator_test                                      PASSED in 0.1s
//dragnn/core:input_batch_cache_test                                     PASSED in 0.3s
//dragnn/core:resource_container_test                                    PASSED in 0.0s
//dragnn/io:sentence_input_batch_test                                    PASSED in 0.3s
//dragnn/python:composite_optimizer_test                                 PASSED in 6.6s
//dragnn/python:digraph_ops_test                                         PASSED in 3.4s
//dragnn/python:evaluation_test                                          PASSED in 2.8s
//dragnn/python:render_parse_tree_graphviz_test                          PASSED in 2.4s
//dragnn/python:render_spec_with_graphviz_test                           PASSED in 2.3s
//dragnn/python:visualization_test                                       PASSED in 1.9s
//syntaxnet:arc_standard_transitions_test                                PASSED in 0.1s
//syntaxnet:binary_segment_state_test                                    PASSED in 0.1s
//syntaxnet:binary_segment_transitions_test                              PASSED in 0.1s
//syntaxnet:char_ngram_string_extractor_test                             PASSED in 0.1s
//syntaxnet:char_properties_test                                         PASSED in 0.1s
//syntaxnet:char_shift_transitions_test                                  PASSED in 0.1s
//syntaxnet:head_transitions_test                                        PASSED in 0.1s
//syntaxnet:label_transitions_test                                       PASSED in 0.1s
//syntaxnet:morphology_label_set_test                                    PASSED in 0.1s
//syntaxnet:once_transitions_test                                        PASSED in 0.1s
//syntaxnet:parser_features_test                                         PASSED in 0.1s
//syntaxnet:segmenter_utils_test                                         PASSED in 0.1s
//syntaxnet:sentence_features_test                                       PASSED in 0.1s
//syntaxnet:shared_store_test                                            PASSED in 0.2s
//syntaxnet:tagger_transitions_test                                      PASSED in 0.1s
//syntaxnet/util:check_test                                              PASSED in 1.7s
//syntaxnet/util:registry_test                                           PASSED in 2.7s
//syntaxnet:whole_sentence_features_test                                 PASSED in 0.1s
//util/utf8:unicodetext_unittest                                         PASSED in 0.0s
//dragnn/python:bulk_component_test                                      FAILED in 3.6s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/dragnn/python/bulk_component_test/test.log
//dragnn/python:graph_builder_test                                       FAILED in 109.3s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/dragnn/python/graph_builder_test/test.log
//dragnn/python:lexicon_test                                             FAILED in 3.3s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/dragnn/python/lexicon_test/test.log
//dragnn/python:network_units_test                                       FAILED in 3.6s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/dragnn/python/network_units_test/test.log
//dragnn/python:sentence_io_test                                         FAILED in 3.4s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/dragnn/python/sentence_io_test/test.log
//dragnn/python:spec_builder_test                                        FAILED in 3.5s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/dragnn/python/spec_builder_test/test.log
//dragnn/tools:model_trainer_test                                        FAILED in 24.5s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/dragnn/tools/model_trainer_test/test.log
//examples/dragnn:test_run_all_tutorials                                 FAILED in 4.5s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log
//syntaxnet:beam_reader_ops_test                                         FAILED in 19.8s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 11.8s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 3.1s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 11.3s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 5.4s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 3.0s
  /tmp/bazeltemp/_bazel_root/496ef57d77987a9f471821c181b6cf0f/execroot/__main__/bazel-out/local_linux-opt/testlogs/syntaxnet/text_formats_test/test.log

Executed 52 out of 52 tests: 38 tests pass and 14 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

```

**Comment by tomodachi21** [comment]
UDPATE: Looks like you can ignore the above updates - the segmentation fault is being caused by the out-of-memory GPU crashing. You can easily fix this by replacing the lines in the models/syntaxnet/syntaxnet/parser_eval.py in the Main() function call to this:

```
gpu_opt = tf.GPUOptions(allow_growth=True)
with tf.Session(config=tf.ConfigProto(gpu_options=gpu_opt)) as sess:
    Eval(sess)

```
Thanks to @utkrist https://github.com/tensorflow/models/issues/173

I will post a little step-by-step for those who are looking at this - spent probably 2 days recompiling this (takes about 2-3 hrs each time you compile it... really ridiculous Google has not provided instructions on GPU integration. Now that being said - one more question hopefully someone more advanced can help with.
https://github.com/tensorflow/models/issues/173

Even though it runs with the GPU it looks like it may error out or crash after completion?
```
INFO:tensorflow:Processed 1 documents
INFO:tensorflow:Total processed documents: 1
INFO:tensorflow:num correct tokens: 0
INFO:tensorflow:total tokens: 6
INFO:tensorflow:Seconds elapsed in evaluation: 1.30, eval metric: 0.00%
INFO:tensorflow:Processed 1 documents
INFO:tensorflow:Total processed documents: 1
INFO:tensorflow:num correct tokens: 1
INFO:tensorflow:total tokens: 6
INFO:tensorflow:Seconds elapsed in evaluation: 1.59, eval metric: 16.67%
INFO:tensorflow:Read 1 documents
Input: why are you looking at me
Parse:
looking VBG ROOT
 +-- why WRB advmod
 +-- are VBP aux
 +-- you PRP nsubj
 +-- at IN prep
     +-- me PRP pobj
syntaxnet/demo.sh: line 56: 32245 Segmentation fault      (core dumped) $PARSER_EVAL --input=$INPUT_FORMAT --output=stdout-conll --hidden_layer_sizes=64 --arg_prefix=brain_tagger --graph_builder=structured --task_context=$MODEL_DIR/context.pbtxt --model_path=$MODEL_DIR/tagger-params --slim_model --batch_size=1024 --alsologtostderr
     32246                       (core dumped) | $PARSER_EVAL --input=stdin-conll --output=stdout-conll --hidden_layer_sizes=512,512 --arg_prefix=brain_parser --graph_builder=structured --task_context=$MODEL_DIR/context.pbtxt --model_path=$MODEL_DIR/parser-params --slim_model --batch_size=1024 --alsologtostderr
     32247                       (core dumped) | bazel-bin/syntaxnet/conll2tree --task_context=$MODEL_DIR/context.pbtxt --alsologtostderr
```

**Comment by tomodachi21** [comment]
One final question - for anyone who might be an expert user out there. It looks like the annotator is working correctly through the script but I noticed that it takes a long time to actually load the models - not that long to actually evaluate the sentence itself. 

Is there a way to keep the model loaded and then pass new lines of text to it. I know that you can pass it a file with multiple lines but I want to keep the thread hanging in the background and be able to pass strings into it. Not sure if this is possible but would really appreciate anyone's guidance on the matter.

Thanks!

**Comment by zerodarkzone** [comment]
I'm still getting crashes because of cuda out of memory errors. 
Even after using: `gpu_opt = tf.GPUOptions(allow_growth=True)`
I'm compiling with bazel 0.5.4 and my GPU is a NVIDIA1080TI

**Comment by xiaoleihuang** [comment]
@perdasilva 
I tried to install NCCL 2*, the latest version, but the tensorflow can not locate the NCCL. Have you tried the version 2? Thanks!

**Comment by cyberwillis** [comment]
Hi, I have compiled successful tensorflow 1.8 with NCCL2, the problem is if you have used the deb package to install it on your system, then the package was splitted in different locations:

- *lib* **content** to **/usr/lib/x86_64-linux-gnu/** folder
- *include* **content** to **/usr/include/** folder
- *NCCL-SLA* (software license agreement) to python somewhere in **site-packages** folder

However Tensorflow configuration needs only one path for the root of this content, that's why the compilation is not happy.

To solve this you can:

1. create a folder and put symlinks pointing to this exact structure like this (for example the lastest version 2.1.15):

nccl2 (or the name you like it)
 │
 ├── include
 │      └── nccl.h
 ├── lib
 │      ├── libnccl.so -> libnccl.so.2*
 │      ├── libnccl.so.2 -> libnccl.so.2.1.15*
 │      ├── libnccl.so.2.1.15*
 │      └── libnccl_static.a
 ├── NCCL-SLA.txt
 ├── COPYRIGHT.txt

2. Or download and extract in some where one of this packages accordingly to your cuda version. You can find easly this packages on web:
  - nccl_2.1.15-1%2Bcuda8.0_x86_64.txz
  - nccl_2.1.15-1%2Bcuda9.0_x86_64.txz
  - nccl_2.1.15-1%2Bcuda9.1_x86_64.txz
  
3. Pointing the path on the ./configure process when asked or setting the environment variable for it and it will not be asked.
   export TF_NCCL_VERSION='2.1.15'
   export NCCL_INSTALL_PATH=<path to nccl2 folder>

**Comment by rickragv** [comment]
Hi i m using new tf_serving 
third_party/nccl/nccl.h: No such file or directory 
and i am not finding BUILD file in new directory , can anybody knows

**Comment by cyberwillis** [comment]
Hi .. 

I don't know If I am wrong in your case but the fact is. 

During the configure step of tensorflow prior to build, it asks about the folder of your nccl right ? in that time as I explained above you mus that that structure. 

If you installed nccl from deb the files had splited around your system and not follow the structure tensorflow is waiting for.

**Comment by rickragv** [comment]
thanks cyber,
but in current release they don't have configure file.. its all bazel based.

**Comment by cyberwillis** [comment]
I built yesterday without any problem. I will check again

**Comment by rickragv** [comment]
is it latest 1.7 serving

**Comment by cyberwillis** [comment]
Hi again, 

I don't had time to build it yet to check your needs but I can tell that in my machine I have this file.

.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/external/local_config_nccl
the build is inside this folder..

To get that you have to build tensorflow... (warning it can take several hours to build)

**Comment by cyberwillis** [comment]
Hi... 

I am checking it right now, and yes I understand what you said, but the thing is, the configure file from tensorflow just to register the environment variables that bazel build needs.

**Comment by rickragv** [comment]
yeah..
i tried using 1.4 and it suceded
but to be future ready.. i need 1.7 tf serving..
and all the environment variables perfectly set.. even though i built nccl locally and pointed to it. 
i deleted cache and re-ran still its not finding nccl.h
if in future you try building 1.7 or latest just let us know....

**Comment by cyberwillis** [comment]
Tell me what version of Cuda do you have and what version of Nccl do you have  and also any thing else I can replicate your environtment.

**Comment by cyberwillis** [comment]
How did you set up your nccl2 ?

**Comment by cyberwillis** [comment]
@cjhkeep  
I dont have any problem with nccl.h 1.3 or 2.xx at all.

However if you install "NCCL2" using the ".deb" version your nccl.h will be far away from tensorflow expect to find! That's why a suggested installing from the tar file.

**Comment by discordianfish** [comment]
Wouldn't it be the right way to tensorflow to just look at the right directories? `/usr/include/` is the place for header files in linux, I don't get why it looks somewhere else..?

**Comment by cyberwillis** [comment]
NVIDIA in times to times change the locations of its packages (because they think its funny) :) 
If you investigate a little, depending on your cuda version some files go to some places others go to another places... I believe NVidia doesn't have a stable ideia where to put this things exacly and tensorflow cannot enter on their hell.

**Comment by gautamvasudevan** [comment]
Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment. The GPU build addresses the NCCL dependency.

**Comment by praeclarum** [comment]
@gautamvasudevan This is still a bug when trying to do macOS GPU builds. Since your Docker example doesn't work on Mac, I think this issue should still be open.

**Comment by cyberwillis** [comment]
Hi @praeclarum I am sorry to see your question only now, sadlly I am not using Tensorflow anymore, but I believe that since the Docker Tensorflow rely on the abstract install from Ubuntu you can change it for the exact problem you having. Can you post exact what problem are you getting on your MAC ?

**Comment by cyberwillis** [comment]
In case you really want to try make the GPU available inside docker (macOS only) you can try use [XQuartz](https://www.xquartz.org/) take a look on this Gist https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285

**Comment by gautamvasudevan** [comment]
We don't have any official support for macOS and nccl builds currently, though feel free to file a new issue specifically for macOS, we welcome any community support here!

**Comment by gatoatigrado** [comment]
seems that now there's a `--config=nonccl` option you can add to a bazel command, e.g. `bazel build --config=opt --config=cuda --config=nonccl //tensorflow/tools/pip_package:build_pip_package` (dunno if this will work entirely, but it seems to get me past this error ...)

**Comment by praeclarum** [comment]
@gatoatigrado thanks for the tip, that's exactly what I was looking for
