### ISSUE TITLE
Status{code=INTERNAL, description=WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true / nonzero indices.  temp_storage_bytes: 1, status: out of memory

### ISSUE THREAD

**Issue by ssy341** [tensorflow/serving#730]
Hello all,
Here's a problem, I have no idea. I checked on the Google, there is no result about this error. Why would be come out this error?

>Status{code=INTERNAL, description=WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true / nonzero indices.  temp_storage_bytes: 1, status: out of memory

**Comment by chrisolston** [comment]
It looks like your server may have run out of memory, although it's hard to tell from the error message on which device it's trying to allocate the memory. Maybe you can look into which devices you are trying to use, and how much free memory they have when your model is loaded/running.

**Comment by gautamvasudevan** [comment]
Closing due to staleness.

**Comment by cuijianaaa** [comment]
I have solved the seem problem!!! There is no answer anywhere, may be there is some gpu code use a different gpu id from which used by tensorflow.

**Comment by rhdong** [comment]
> I have solved the seem problem!!! There is no answer anywhere, may be there is some gpu code use a different gpu id from which used by tensorflow.

Hi, could you tell us the detail of your resolution, thank you!
